author: elbee-cyber
name: Dylan Knoff

title: FaultPoint
description: >- # this means to ignore newlines until "baseurl:"
  I'm Dylan, a undergraduate CS student at George Mason and independent security researcher. This blog is where I'll post articles relating to CTFs, personal projects, hacking or whatever else is appropiate.

email: dontopenthis@protonmail.com

# social links
twitter_username: elbee_ez
github_username:  elbee-cyber
# rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: dylan.kno
linkedin_username: dylan-knoff
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - blog.md

# Config section the home


# Build settings
markdown: kramdown

jekyll-theme-experiment:
  about:
    avatar : https://i.pinimg.com/originals/d0/70/71/d07071a12b468ac4afc310f7e42066b9.gif

  portfolio:
    title: Portfolio
    projects:

      - name: Jekyll Theme experiment
        github: https://github.com/anxhe/jekyll-theme-experiment
        img_relative_url: /assets/example.png

      - name: Jekyll Theme experiment
        github: https://github.com/anxhe/jekyll-theme-experiment
        img_relative_url: /assets/example.png

  tools:
    title: Tools and Experience
    icons:
      - relative_url: /assets/icons/bitbucket/bitbucket-original.svg
      - relative_url: /assets/icons/heroku/heroku-original.svg
      - relative_url: /assets/icons/git/git-original.svg
      - relative_url: /assets/icons/express/express-original.svg
      - relative_url: /assets/icons/angularjs/angularjs-original.svg

exclude:
  - Gemfile
  - Gemfile.lock
